name: mock-api-dev
services:
  # http://localhost:8080/docs
  mock-api:
    image: "ccie-gitlab.ccie.cisco.com:4567/mozart/microservices/mock-and-roll/mock-and-roll:v0.1.0"
    command:
      [
        "uvicorn",
        "src.main:app",
        "--proxy-headers", # Include proxy headers from Dockerfile CMD
        "--host",
        "0.0.0.0",
        "--port",
        "8080", # Ensure it runs on 8080 to match port mapping
        "--reload", # Keep reload for development convenience
      ]
    ports:
      - 8080:8080
    environment:
      # Redis Configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      
      # Application Configuration
      LOG_LEVEL: DEBUG
      APP_TITLE: Mock API Server
      
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      # - ./configs/vmanage/:/app/config # Mounts the test config directory...
    depends_on:
      - redis
    networks:
      - mock-api-network

  # Redis cache server
  # redis-cli -h localhost -p 6379 keys '*'
  redis:
    image: redis:8.0.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mock-api-network
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  mock-api-network:
    driver: bridge
