site_name: Mock-and-Roll
site_description: A highly configurable and extensible mock REST API server built with FastAPI
site_url: https://bvandewe.github.io/mock-and-roll/
docs_dir: docs
site_dir: site

repo_name: bvandewe/mock-and-roll
repo_url: https://github.com/bvandewe/mock-and-roll 
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quick-start.md
    - Configuration: configuration.md
  - Server Features:
    - Features Overview: features.md
    - Configuration-Driven API: features/config-driven-api.md
    - Authentication Methods: features/authentication.md
    - Conditional Responses: features/conditional-responses.md
    - Persistence & Redis: features/persistence.md
    - Logging & Monitoring: features/logging.md
    - Template Variables: features/template-variables.md
  - User Guide:
    - CLI Commands: user-guide/cli-commands.md
    - Server Management: user-guide/server-management.md
    - Log Analysis: features/search-functionality.md
  - Configuration Reference:
    - API Configuration: reference/api-config.md
    - Authentication Config: reference/auth-config.md
    - Endpoints Config: reference/endpoints-config.md
    - Configuration Schema: reference/configuration-schema.md
  - Architecture:
    - Overview: architecture/overview.md
    - CLI Design: architecture/cli-design.md
  - Development:
    - Contributing: development/contributing.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Advanced Patterns: examples/advanced-patterns.md
  - Reference:
    - API Reference: reference/api-reference.md
    - Diagrams & Visualizations: reference/diagrams.md
  - Changelog: changelog.md

theme:
  name: material
  # logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      title: On this page
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mermaid2:
      arguments:
        theme: auto

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bvandewe/mock-and-roll
      name: GitHub Repository

extra_css:
  - stylesheets/extra.css
